//
//  CategoryWorker.swift
//  CleanSwift
//
//  Created by Cesar Brenes on 4/25/20.
//  Copyright (c) 2020 VeuxLabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CategoryStoreProcol {
    func insert(category: Category, completionHandler:() -> Void)
    func fetchAll(completionHandler:(_ categories: [Category]) -> Void)
}

class CategoryWorker {
    
    var store: CategoryStoreProcol
    
    init(store: CategoryStoreProcol) {
        self.store = store
    }
  
    func insert(category: Category, completionHandler:() -> Void) {
        store.insert(category: category, completionHandler: completionHandler)
    }
    
    func fetchAll(completionHandler:(_ categories: [Category]) -> Void) {
        store.fetchAll(completionHandler: completionHandler)
    }
}
