//
//  CategoriesWorker.swift
//  CleanSwift
//
//  Created by Cesar Brenes on 4/25/20.
//  Copyright (c) 2020 VeuxLabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CategoriesWorker
{
  func doSomeWork()
  {
  }
}
